apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: test
    - name: MYSQL_USER
      value: grad
    - name: MYSQL_PASSWORD
      valueFrom:
          secretKeyRef:
            name: root-password
            key: mysql_root_password
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
          secretKeyRef:
            name: root-password
            key: mysql_root_password