pipeline {

  environment {
        IMG_NAME = "node-app-grad"
        NEXUS_REPO = "nexus-repo.tools.svc.cluster.local:9001"
    }

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile 'CI/builder.yaml'
    }
  }

  stages {
    
    stage('Kaniko Build & Push Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/app/Dockerfile \
                             --context `pwd`/app \
                             --destination=${NEXUS_REPO}/${IMG_NAME}
            '''
          }
        }
      }
    }
  }
}

//  create secret docker-registry nexus-cred --docker-server=nexus-repo.tools.svc.cluster.local:9001 --docker-username=admin --docker-password=admin123